spring:
  flyway:
    baseline-on-migrate: true
  codec:
    max-in-memory-size=100MB:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://klx-test-dbpostgresql-1:5432/dbtest
    username: postgres
    password: password
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

springdoc:
  api-docs:
    path=/api-docs:


